spring:
  application:
    name: service-a
  cloud:
    config:
      discovery:
        enabled: true
  config:
    import:
    - 'optional:configserver:'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    health:
      show-details: always
#https://github.com/spring-cloud/spring-cloud-bus/issues/246 : MARCHE TOUJOURS :-(      
    restart:
      enabled: false
    pause:
      enabled: false
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
      
logging:
  level:
    root: OFF
    '[org.springframework.boot.context.config]': INFO